### ISSUE TITLE
Connect labels to github projects

### ISSUE THREAD

**Issue by tamriq** [sorrentum/sorrentum#207]
As far as I understand we can create a chain of actions using GitHub Actions and set up a workflow that triggers when a label is added to an issue or pull request and then automatically moves the associated card to a specific project and column.

We need to create yml file in `.github/workflows` with the following content:

```
on:
  issues:
    types:
      - labeled
  pull_request:
    types:
      - labeled
      
 env:
  PROJECT_ID: <project_id>
  COLUMN_NAME: <column_name>
  LABEL_NAME: <label_name>

jobs:
  move_card:
    runs-on: ubuntu-latest
    steps:
      - name: Move card to project
        uses: actions/github-script@v5 (no sure if the version is 5)
        with:
          script: |
            // JavaScript code here
```

In the script section, we'll need to write JavaScript code to find the card associated with the issue or pull request, check if the specified label has been added, and move the card to the specified project and column.
